apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: $kubernetes_version
api:
  advertiseAddress: $apiserver_advertise_address
etcd:
  endpoints:
  - https://$ip:2379
  caFile: /etc/kubernetes/pki/etcd/ca.pem
  certFile: /etc/kubernetes/pki/etcd/client.pem
  keyFile: /etc/kubernetes/pki/etcd/client-key.pem
  dataDir: $etcd_data_dir
networking:
  podSubnet: $pod_network_cidr
  serviceSubnet: $service_cidr
apiServerCertSANs:
- 127.0.0.1
- $hostname
- $ip
tokenTTL: "0"
